[project]
name = "osvpy"
version = "0.2.0"
description = "Scan container images for vulnerabilities in Python. Built on OSV-Scanner."
readme = "README.md"
requires-python = ">=3.13"
license = "BSD-3-Clause-Clear"
license-files = ["LICENSE"]
dependencies = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Security",
    "Topic :: Software Development :: Quality Assurance",
    "Typing :: Typed",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0",
    "pytest-cov",
    "pytest-crap",
]
local = [
    "mypy",
    "ruff",
    "prek",
]

[tool.pytest.ini_options]
strict = true
addopts = "-ra -vv --crap --cov osvpy --import-mode=importlib"
testpaths = ["tests"]

[tool.mypy]
explicit_package_bases = true
files = ["src/osvpy", "tests", "explore_toolkit"]
strict = true
mypy_path = ["src"]
exclude = ["explore_toolkit/experiments", "explore_toolkit/results"]

[tool.ruff]
unsafe-fixes = false
extend-include = ["README.md"]
extend-exclude = ["explore_toolkit/experiments", "explore_toolkit/results", "experiments"]

[tool.ruff.lint]
extend-select = ["ANN", "ASYNC", "PYI", "PT", "SIM", "TC", "TID", "PERF", "TRY", "PGH003"]
extend-ignore = ["TID252", "TRY003"]
preview = true

[tool.ruff.lint.flake8-type-checking]
strict = true
quote-annotations = true
exempt-modules = []

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"importlib.import_module".msg = "Do not dynamically import modules. Explicitly import them at the top of the file."
"__future__.annotations".msg = "The annotation future statement is disallowed."

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true

[tool.scikit-build]
cmake.build-type = "Release"
install.strip = true
wheel.packages = ["src/osvpy"]
wheel.exclude = ["**/*.pyc", "**/__pycache__/**", "**/*.dSYM/**"]
sdist.inclusion-mode = "explicit"
sdist.include = ["pyproject.toml", "README.md", "LICENSE", "go/*.go", "go/patches/*.patch", "go/go.mod", "go/go.sum", "src/osvpy/*.py", "src/osvpy/*.pyx", "src/osvpy/*.pxd", "src/osvpy/*.pyi", "src/osvpy/py.typed", "CMakeLists.txt"]

[build-system]
requires = ["scikit-build-core>=1.0.3,<1.1", "Cython>=3.3.0,<4"]
build-backend = "scikit_build_core.build"
