from collections.abc import Iterator, Sequence
from typing import Never, overload

class IndexedSequence[T](Sequence[T]):
    def __new__(cls) -> Never: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[T, ...]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def count(self, value: object) -> int: ...
    def index(self, value: object, start: int = 0, stop: int | None = None) -> int: ...

class _View:
    def __new__(cls) -> Never: ...
    @property
    def index(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class BatchResult(_View):
    @property
    def images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def packages(self) -> IndexedSequence[Package]: ...
    @property
    def vulnerabilities(self) -> IndexedSequence[Vulnerability]: ...
    @property
    def advisory_sources(self) -> IndexedSequence[AdvisorySource]: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...
    @property
    def complete(self) -> bool: ...
    @property
    def errors(self) -> tuple[tuple[int, NativeError], ...]: ...

class ImageResult(_View):
    @property
    def requested(self) -> str: ...
    @property
    def os(self) -> str | None: ...
    @property
    def status(self) -> str: ...
    @property
    def diagnostics(self) -> IndexedSequence[NativeError]: ...
    @property
    def occurrences(self) -> IndexedSequence[Occurrence]: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...
    @property
    def packages(self) -> IndexedSequence[Package]: ...
    @property
    def vulnerable_packages(self) -> IndexedSequence[Package]: ...
    @property
    def noncompliant_packages(self) -> IndexedSequence[Package]: ...
    @property
    def vulnerabilities(self) -> IndexedSequence[Vulnerability]: ...
    @property
    def complete(self) -> bool: ...

class Package(_View):
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def ecosystem(self) -> str: ...
    @property
    def commit(self) -> str: ...
    @property
    def os_package_name(self) -> str: ...
    @property
    def purl(self) -> str: ...
    @property
    def present_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def vulnerable_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def noncompliant_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def affected_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...

class Vulnerability(_View):
    @property
    def id(self) -> str: ...
    @property
    def aliases(self) -> IndexedSequence[str]: ...
    @property
    def affected_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...

class AdvisorySource(_View):
    @property
    def id(self) -> str: ...
    @property
    def aliases(self) -> IndexedSequence[str]: ...
    @property
    def summary(self) -> str: ...
    @property
    def modified(self) -> str | None: ...
    @property
    def published(self) -> str | None: ...
    @property
    def withdrawn(self) -> str | None: ...
    @property
    def database_severity(self) -> str | None: ...
    @property
    def severities(self) -> IndexedSequence[ReportSeverity]: ...
    @property
    def references(self) -> IndexedSequence[ReportReference]: ...
    @property
    def affected_images(self) -> IndexedSequence[ImageResult]: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...

class Occurrence(_View):
    @property
    def image(self) -> ImageResult: ...
    @property
    def package(self) -> Package: ...
    @property
    def context(self) -> ReportContext: ...
    @property
    def license_assessment(self) -> ReportLicense: ...
    @property
    def findings(self) -> IndexedSequence[Finding]: ...

class Finding(_View):
    @property
    def occurrence(self) -> Occurrence: ...
    @property
    def advisory_source(self) -> AdvisorySource: ...
    @property
    def fix_evidence(self) -> ReportFix: ...
    @property
    def assessment(self) -> ReportAssessment: ...
    @property
    def vulnerability(self) -> Vulnerability: ...

class ReportContext(_View):
    @property
    def path(self) -> str: ...
    @property
    def source_type(self) -> str: ...
    @property
    def layer(self) -> str | None: ...
    @property
    def dependency_groups(self) -> IndexedSequence[str]: ...

class ReportAssessment(_View):
    @property
    def called(self) -> bool | None: ...
    @property
    def unimportant(self) -> bool | None: ...
    @property
    def max_severity(self) -> str: ...

class ReportLicense(_View):
    @property
    def licenses(self) -> IndexedSequence[str]: ...
    @property
    def policy(self) -> IndexedSequence[str] | None: ...
    @property
    def violations(self) -> IndexedSequence[str]: ...
    @property
    def status(self) -> str: ...

class ReportFix(_View):
    @property
    def versions(self) -> IndexedSequence[str]: ...
    @property
    def status(self) -> str: ...
    @property
    def severities(self) -> IndexedSequence[ReportSeverity]: ...
    @property
    def urgencies(self) -> IndexedSequence[str]: ...

class NativeError(_View):
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...

class ReportSeverity(_View):
    @property
    def type(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def vector(self) -> str: ...

class ReportReference(_View):
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str: ...

class CancellationController:
    def cancel(self) -> None: ...

def scan(payload: bytes, controller: CancellationController) -> BatchResult: ...
