# generated by datamodel-codegen:
#   filename:  response.schema.json

from typing import Any

from pydantic import BaseModel, Field, RootModel


class AdvisoryID(BaseModel):
    publisher: str = Field(..., alias="Publisher")
    reference: str = Field(..., alias="Reference")


class AffectedPackage(BaseModel):
    ecosystem: str | None = None
    name: str | None = None
    purl: str | None = None


class AnalysisInfo(BaseModel):
    called: bool
    unimportant: bool


class BaseImageDetails(BaseModel):
    name: str
    tags: list[str] | None


class Credit(BaseModel):
    contact: list[str] | None = None
    name: str | None = None
    type: str | None = None


class Event(BaseModel):
    fixed: str | None = None
    introduced: str | None = None
    last_affected: str | None = None
    limit: str | None = None


class ExperimentalLicenseConfig(BaseModel):
    allowlist: list[str] | None
    summary: bool


class FindingExploitabilitySignal(BaseModel):
    justification: int = Field(..., alias="Justification")
    plugin: str = Field(..., alias="Plugin")


class GenericFindingAdvisory(BaseModel):
    description: str = Field(..., alias="Description")
    id: AdvisoryID | None = Field(..., alias="ID")
    recommendation: str = Field(..., alias="Recommendation")
    severity: int = Field(..., alias="Sev")
    title: str = Field(..., alias="Title")


class GenericFindingTargetDetails(BaseModel):
    extra: str = Field(..., alias="Extra")


class GroupInfo(BaseModel):
    aliases: list[str] | None
    analysis: dict[str, AnalysisInfo] | None = Field(
        None, alias="experimental_analysis"
    )
    ids: list[str] | None
    max_severity: str


class ImageOriginDetails(BaseModel):
    layer_index: int = Field(..., alias="index")


class LayerMetadata(BaseModel):
    base_image_index: int
    command: str
    diff_id: str
    is_empty: bool


class LicenseCount(BaseModel):
    count: int
    name: str


class NativeError(BaseModel):
    code: str
    message: str


class PackageExploitabilitySignal(BaseModel):
    justification: int = Field(..., alias="Justification")
    matches_all_vulnerabilities: bool = Field(..., alias="MatchesAllVulns")
    plugin: str = Field(..., alias="Plugin")
    vulnerability_ids: list[str] | None = Field(..., alias="VulnIdentifiers")


class PackageInfo(BaseModel):
    commit: str | None = None
    deprecated: bool | None = None
    ecosystem: str
    image_origin: ImageOriginDetails | None = Field(None, alias="image_origin_details")
    name: str
    os_package_name: str | None = None
    version: str


class Range(BaseModel):
    database_specific: dict[str, Any] | None = None
    events: list[Event] | None = None
    repo: str | None = None
    type: str | None = None


class Reference(BaseModel):
    type: str | None = None
    url: str | None = None


class ScanMetadata(BaseModel):
    all_packages: bool
    duration_seconds: float
    image_digest: str | None = None
    image_platform: str | None = None
    no_packages: bool
    offline: bool
    scanner_version: str
    source: str


class Severity(BaseModel):
    score: str | None = None
    source: str | None = None
    type: str | None = None


class SourceInfo(BaseModel):
    path: str
    type: str


class Affected(BaseModel):
    database_specific: dict[str, Any] | None = None
    ecosystem_specific: dict[str, Any] | None = None
    package: AffectedPackage | None = None
    ranges: list[Range] | None = None
    severity: list[Severity] | None = None
    versions: list[str] | None = None


class ExperimentalAnalysisConfig(BaseModel):
    licenses: ExperimentalLicenseConfig


class GenericFinding(BaseModel):
    advisory: GenericFindingAdvisory | None = Field(..., alias="Adv")
    exploitability_signals: list[FindingExploitabilitySignal] | None = Field(
        ..., alias="ExploitabilitySignals"
    )
    plugins: list[str] | None = Field(..., alias="Plugins")
    target: GenericFindingTargetDetails | None = Field(..., alias="Target")


class ImageMetadata(BaseModel):
    base_images: list[list[BaseImageDetails] | None] | None
    layers: list[LayerMetadata] | None = Field(..., alias="layer_metadata")
    os: str


class Advisory(BaseModel):
    affected: list[Affected] | None = None
    aliases: list[str] | None = None
    credits: list[Credit] | None = None
    database_specific: dict[str, Any] | None = None
    details: str | None = None
    id: str | None = None
    modified: str | None = None
    published: str | None = None
    references: list[Reference] | None = None
    related: list[str] | None = None
    schema_version: str | None = None
    severity: list[Severity] | None = None
    summary: str | None = None
    upstream: list[str] | None = None
    withdrawn: str | None = None


class Package(BaseModel):
    dependency_groups: list[str] | None = None
    groups: list[GroupInfo] | None = None
    license_violations: list[str] | None = None
    licenses: list[str] | None = None
    package: PackageInfo
    vulnerabilities: list[Advisory] | None = None


class PackageSource(BaseModel):
    exploitability_signals: list[PackageExploitabilitySignal] | None = Field(
        None, alias="experimental_pes"
    )
    packages: list[Package] | None
    source: SourceInfo


class ScanData(BaseModel):
    analysis_config: ExperimentalAnalysisConfig = Field(
        ..., alias="experimental_config"
    )
    generic_findings: list[GenericFinding] | None = Field(
        None, alias="experimental_generic_findings"
    )
    image_metadata: ImageMetadata | None = None
    license_summary: list[LicenseCount] | None = None
    sources: list[PackageSource] | None = Field(..., alias="results")


class NativeResponse(BaseModel):
    abi_version: int
    error: NativeError | None = None
    metadata: ScanMetadata | None = None
    ok: bool
    result: ScanData | None = None


class Model(RootModel[NativeResponse]):
    root: NativeResponse
