# generated by datamodel-codegen:
#   filename:  response.schema.json

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AdvisoryID(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    publisher: str = Field(..., alias="Publisher")
    reference: str = Field(..., alias="Reference")


class AffectedPackage(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    ecosystem: str | None = None
    name: str | None = None
    purl: str | None = None


class AnalysisInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    called: bool
    unimportant: bool


class BaseImageDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    name: str
    tags: list[str] | None


class Credit(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    contact: list[str] | None = None
    name: str | None = None
    type: str | None = None


class Event(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fixed: str | None = None
    introduced: str | None = None
    last_affected: str | None = None
    limit: str | None = None


class ExperimentalLicenseConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    allowlist: list[str] | None
    summary: bool


class FindingExploitabilitySignal(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    justification: int = Field(..., alias="Justification")
    plugin: str = Field(..., alias="Plugin")


class GenericFindingAdvisory(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    description: str = Field(..., alias="Description")
    id: AdvisoryID | None = Field(..., alias="ID")
    recommendation: str = Field(..., alias="Recommendation")
    severity: int = Field(..., alias="Sev")
    title: str = Field(..., alias="Title")


class GenericFindingTargetDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    extra: str = Field(..., alias="Extra")


class GroupInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    aliases: list[str] | None
    analysis: dict[str, AnalysisInfo] | None = Field(
        None, alias="experimental_analysis"
    )
    ids: list[str] | None
    max_severity: str


class ImageOriginDetails(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    layer_index: int = Field(..., alias="index")


class LayerMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    base_image_index: int
    command: str
    diff_id: str
    is_empty: bool


class LicenseCount(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    count: int
    name: str


class LicenseViolation(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    forbidden: list[str]
    licenses: list[str]
    package: str


class NativeError(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    code: str
    message: str


class PackageExploitabilitySignal(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    justification: int = Field(..., alias="Justification")
    matches_all_vulnerabilities: bool = Field(..., alias="MatchesAllVulns")
    plugin: str = Field(..., alias="Plugin")
    vulnerability_ids: list[str] | None = Field(..., alias="VulnIdentifiers")


class PackageFinding(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    fixed_versions: list[str]
    id: str


class PackageInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    commit: str | None = None
    deprecated: bool | None = None
    ecosystem: str
    image_origin: ImageOriginDetails | None = Field(None, alias="image_origin_details")
    name: str
    os_package_name: str | None = None
    version: str


class PackageSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    ecosystem: str
    id: str
    installed_version: str
    name: str
    vulnerabilities: list[PackageFinding]


class Range(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    database_specific: dict[str, Any] | None = None
    events: list[Event] | None = None
    repo: str | None = None
    type: str | None = None


class Reference(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    type: str | None = None
    url: str | None = None


class ScanMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    all_packages: bool
    duration_seconds: float
    image_digest: str | None = None
    image_platform: str | None = None
    no_packages: bool
    offline: bool
    scanner_version: str
    source: str


class Severity(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    score: str | None = None
    source: str | None = None
    type: str | None = None


class Rating(StrEnum):
    unknown = "unknown"
    none = "none"
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class SeveritySummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    rating: Rating
    score: float | None


class SourceInfo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    path: str
    type: str


class VulnerabilitySummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    aliases: list[str]
    id: str
    packages: list[str]
    severity: SeveritySummary


class Affected(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    database_specific: dict[str, Any] | None = None
    ecosystem_specific: dict[str, Any] | None = None
    package: AffectedPackage | None = None
    ranges: list[Range] | None = None
    severity: list[Severity] | None = None
    versions: list[str] | None = None


class ExperimentalAnalysisConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    licenses: ExperimentalLicenseConfig


class GenericFinding(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    advisory: GenericFindingAdvisory | None = Field(..., alias="Adv")
    exploitability_signals: list[FindingExploitabilitySignal] | None = Field(
        ..., alias="ExploitabilitySignals"
    )
    plugins: list[str] | None = Field(..., alias="Plugins")
    target: GenericFindingTargetDetails | None = Field(..., alias="Target")


class ImageMetadata(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    base_images: list[list[BaseImageDetails]] | None
    layers: list[LayerMetadata] | None = Field(..., alias="layer_metadata")
    os: str


class LicenseReport(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    allowed_licenses: list[str]
    violations: list[LicenseViolation]


class ScanResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    image: str
    licenses: LicenseReport | None = None
    metadata: ScanMetadata
    packages: list[PackageSummary]
    vulnerabilities: list[VulnerabilitySummary]


class Advisory(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    affected: list[Affected] | None = None
    aliases: list[str] | None = None
    credits: list[Credit] | None = None
    database_specific: dict[str, Any] | None = None
    details: str | None = None
    id: str | None = None
    modified: str | None = None
    published: str | None = None
    references: list[Reference] | None = None
    related: list[str] | None = None
    schema_version: str | None = None
    severity: list[Severity] | None = None
    summary: str | None = None
    upstream: list[str] | None = None
    withdrawn: str | None = None


class Package(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dependency_groups: list[str] | None = None
    groups: list[GroupInfo] | None = None
    license_violations: list[str] | None = None
    licenses: list[str] | None = None
    package: PackageInfo
    vulnerabilities: list[Advisory] | None = None


class PackageSource(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    exploitability_signals: list[PackageExploitabilitySignal] | None = Field(
        None, alias="experimental_pes"
    )
    packages: list[Package] | None
    source: SourceInfo


class FullScanData(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    analysis_config: ExperimentalAnalysisConfig = Field(
        ..., alias="experimental_config"
    )
    generic_findings: list[GenericFinding] | None = Field(
        None, alias="experimental_generic_findings"
    )
    image: str
    image_metadata: ImageMetadata | None = None
    license_summary: list[LicenseCount] | None = None
    metadata: ScanMetadata
    sources: list[PackageSource] | None = Field(..., alias="results")


class NativeResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    abi_version: int
    error: NativeError | None = None
    ok: bool
    report: ScanResult | None = None
    result: FullScanData | None = None


class Model(RootModel[NativeResponse]):
    root: NativeResponse
