name: CI

on:
    push:

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    python:
        strategy:
            fail-fast: false
            matrix:
                python: ["3.13", "3.14", "3.14t"]
                platform: [ubuntu-latest, macos-14]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-go@v7
              with:
                  go-version-file: go/go.mod
                  cache-dependency-path: go/go.sum

            - uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python }}
            - uses: astral-sh/setup-uv@v9.0.0

            - name: Install package and test dependencies
              run: uv sync --locked --no-editable --group dev --python "$(command -v python)"

            - name: Run Python unit tests
              run: uv run pytest

    go:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-go@v7
              with:
                  go-version-file: go/go.mod
                  cache-dependency-path: go/go.sum

            - name: Run Go unit tests
              working-directory: go
              run: |
                  go mod vendor
                  git apply patches/*.patch
                  go test -mod=vendor -race ./...
